dist: trusty
sudo: true

language: php

addons:
  chrome: stable
  apt:
    packages:
    - ghostscript

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor
    - $BUILD_CACHE_DIR

php:
#  - 5.6
#  - 7.0
  - 7.1

matrix:
  fast_finish: true

services:
  - elasticsearch

mysql:
  database: kunstmaanbundles
  username: travis
  encoding: utf8

env:
  global:
    - DB="mysql"
    - BUILD_CACHE_DIR=$HOME/.build-cache
    - TRAVIS_BUILD_DIR=.travis/build

before_install:
  - .travis/before_install.sh

install:
  - .travis/install.sh

before_script:
  - .travis/before_script.sh

script:
  - .travis/script.sh

after_failure:
  - .travis/after_failure.sh

#notifications:
#  email:
#    - travis@kunstmaan.be
